version: '3.7'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
  app:
    build:
      context: cognate-app
      dockerfile: Dockerfile
  caddy:
    image: caddy:2.5.1
    ports:
      - 5000:5000
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: