version: '3.7'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: server
    ports:
      - 5001:5000
    volumes:
      - ./server:/usr/app